### ISSUE TITLE
Smile4ever comments

### ISSUE THREAD

**Issue by jonathanKingston** [jonathanKingston/sea-containers#26]
So I don't lose them, @smile4ever mentioned this

- [x] Hide pointer on sidebar tab elements - **Covered by #27**
- [x] More padding for tabs  - **Covered by #13**
- [x] Less padding for container headers in the sidebar  - **Covered by #13**
- [x] Make a context menu resembling the default when right clicking on a tab  - **Covered by #28**
- [x] Make a context menu (or none) for container headers   - **Covered by #29**
- [x] Scrolling isn't optimal either, if I click the last tab in my "Default" group it always scrolls to the bottom (why not keep the scroll? If I  can click the item, it's viewable) - **Covered in #18**
- [x]  I notice when I close a tab in my personal container, it doesn't update the counter - **Covered by #11**
- [x] I don't like how pinned tabs are rendered - **Wont fix**
- [x] Option to hide tab bar (when https://bugzilla.mozilla.org/show_bug.cgi?id=1332447 is ready)
- [x] Detect fullscreen, hide/open sidebar when https://bugzilla.mozilla.org/show_bug.cgi?id=1341126 lands
- [x] Also, when I click "Hide this container" in the Containers addon, the container header Personal isn't hidden (I expected that to happen, but it didn't) - maybe gray it out?
- [x] An option to set what happens if you click the container header would be welcome - if I click a container header I want the last used tab focused again
- [x] If I click on the container header and there is no last used tab, pick the first, if there are no tabs, create a new, empty tab

**Comment by jonathanKingston** [comment]
> Hide pointer on sidebar tab elements

Do you mean that you get the cursor hand when hovering over a tab item? This was intentional, yes Firefox itself doesn't have this convention however I personally think anything clickable should have a cursor.

> More padding for tabs

I agree, however anything more than 1px top and bottom will likely create bloat

> Option to hide tab bar (when https://bugzilla.mozilla.org/show_bug.cgi?id=1332447 is ready)

I dunno how I am going to do options yet but yeah certainly this will be an option. There is talk of having an actual sidebar here for tabs rather than just a normal sidebar. Anyway and progressions on getting tab center we should add here.

**Comment by jonathanKingston** [comment]
> Less padding for container headers in the sidebar

I think you might mean margin here?

> Make a context menu resembling the default when right clicking on a tab

This is already the case, I spoke to web extension folk about removing the default ones for a link below the ones I added and this currently isn't possible without capturing the right click and drawing my own context menu which is ugly. But yeah there is pin, mute and reload.

Are the others you need out of this menu? The others don't add much value to me really.

**Comment by jonathanKingston** [comment]
> Make a context menu (or none) for container headers

I had expected to add some items here, like mute container which could never allow an unmuted tab etc, reload all. All planned but not a priority. Again the default options here are not super helpful, raised with webext people.

> Detect fullscreen, hide/open sidebar when https://bugzilla.mozilla.org/show_bug.cgi?id=1341126 lands

Yeah or just certain percentage of the content area, on my laptop screen it's annoying to have two windows tiled with both having sidebars. However attached to my 27 inch screen at work having 2/3 open isn't a problem and is useful.

> Also, when I click "Hide this container" in the Containers addon, the container header Personal isn't hidden (I expected that to happen, but it didn't) - maybe gray it out?

I currently can't detect assignments or hiding, both features are stored within the experiment. We either would have to allow messaging cross extension or bake these into the platform with APIs. It was something I was expecting people to ask for. (Having right click show assignments would be super useful with the sidebars real estate etc).

**Comment by jonathanKingston** [comment]
> An option to set what happens if you click the container header would be welcome - if I click a container header I want the last used tab focused again

>  If I click on the container header and there is no last used tab, pick the first, if there are no tabs, create a new, empty tab

Agreed on both counts, I actually had the blank container creating a new tab idea myself but was worried about the users being confused about the duality of clicking a header.
I initially had it opening the first tab always and that was a little confusing, I guess keeping state of last opened tab per container might make this less ugly. I'm really not a huge fan of options especially when something is new as it adds a lot of complexity... I would rather get a feature right, I like the direction though.

> Another thing maybe: I don't like how pinned tabs are rendered

Hmm can you explain a little, I agree I have some issues with the appearance but I'm not sure what you mean.

**Comment by Smile4ever** [comment]
> Do you mean that you get the cursor hand when hovering over a tab item? This was intentional, yes Firefox itself doesn't have this convention however I personally think anything clickable should have a cursor.

Yes. Then make it optional, please.

> I agree, however anything more than 1px top and bottom will likely create bloat

1px at top & bottom it is.

> Option to hide tab bar (when https://bugzilla.mozilla.org/show_bug.cgi?id=1332447 is ready)
>> I dunno how I am going to do options yet but yeah certainly this will be an option.

Great. I could help with creating an options page.

> Less padding for container headers in the sidebar
>> I think you might mean margin here?

Sure thing, margin.

> Make a context menu resembling the default when right clicking on a tab
>> This is already the case, I spoke to web extension folk about removing the default ones for a link below the ones I added and this currently isn't possible without capturing the right click and drawing my own context menu which is ugly. But yeah there is pin, mute and reload.

>> Are the others you need out of this menu? The others don't add much value to me really.

I would like "Move to new Window" as well. If it becomes possible to remove the default context menu items, that would be super nice to do. Right now I have a lot of items there that I don't need or want.

> Make a context menu (or none) for container headers
>> I had expected to add some items here, like mute container which could never allow an unmuted tab etc, reload all. All planned but not a priority. Again the default options here are not super helpful, raised with webext people.

Please catch the right click event here and cancel the context menu rendering event for now.

> Agreed on both counts, I actually had the blank container creating a new tab idea myself but was worried about the users being confused about the duality of clicking a header.
> I initially had it opening the first tab always and that was a little confusing, I guess keeping state of last opened tab per container might make this less ugly. I'm really not a huge fan of options especially when something is new as it adds a lot of complexity... I would rather get a feature right, I like the direction though.

I think it's the most intuitive to always open the last open tab for a certain container. What the fallback should be (a tab with tabid nearest to the last open tabid or just the first tab of the container) I'm not so certain. It is probably best to try this by writing the code first.

> Another thing maybe: I don't like how pinned tabs are rendered

Look at how they are rendered at Tab Center. I feel the consistency is completely missing the way they are rendered now.

**Comment by jonathanKingston** [comment]
> Yes. Then make it optional, please.

I'm not making mundane things like this optional. I will make sure everything has hover and focus feedback and remove it. I still disagree however I'm not exactly fussed. Millions of options is just ugly confusing and breaks things.

Raised #27 for this.

> 1px at top & bottom it is.
> Sure thing, margin.

Will be handled in #13 

> Great. I could help with creating an options page.

I'm going to wait for some form of convention here. Tab center has the preference page which would be nice if Web Extensions can all do natively. I'm not in a rush to add options anyway.

> I would like "Move to new Window"
#28

> Please catch the right click event here and cancel the context menu rendering event for now.

#29

> I think it's the most intuitive to always open the last open tab for a certain container. What the fallback should be (a tab with tabid nearest to the last open tabid or just the first tab of the container) I'm not so certain. It is probably best to try this by writing the code first.

The biggest problem with this is actually that you might be in a personal tab and clicking on work heading changes tab rather than opening it to peak inside. The user will click the heading and not know what they will be jumping into.

> Look at how they are rendered at Tab Center. I feel the consistency is completely missing the way they are rendered now.

Currently tab centre looks super ugly on nightly (they even have a warning about it's deprecation in 55 - which is why I'm working hard to support their features)

![selection_679](https://user-images.githubusercontent.com/338988/26882344-0755302a-4b92-11e7-9b54-069ef6785983.png)

I personally think showing the title is pretty intrusive. I like that the pinned tabs are still visible when the tab is collapsed etc.

![selection_682](https://user-images.githubusercontent.com/338988/26882403-3773befc-4b92-11e7-9dd7-5fa58154b962.png)

This is the similar view to tab center.

Are you asking for them to appear as a full row? Currently people pin horizontal tabs and the title hides, it's main use case is for when you recognise the favicon. There is a current bug about unpinning tabs being messed up FYI #17 and adding the glow #8.

**Comment by Smile4ever** [comment]
> Are you asking for them to appear as a full row?

Yes, just like Tab Center (but no messed up widths please).

**Comment by jonathanKingston** [comment]
> Yes, just like Tab Center (but no messed up widths please).

Unfortunately I would rather just keep them how they are with some tweaks to how they are aligned.

I would rather align with horizontal tabs for a few reasons:

- I would like the pinned tabs always visible
- Sorting is possible for the use case you are after
- I don't want to show a row within the container when it's closed
- Vertical space is at a premium

If I get other interest to add this I will consider an option perhaps, however more options adds more complexity.

To be clear, I am super grateful for all your feedback!
