### ISSUE TITLE
Overview: Features and Bugs

### ISSUE THREAD

**Issue by tradewatcher** [jonathanKingston/sea-containers#59]
Hello @jonathanKingston 

I use Sea Container since ~12 Months and wanted to make a list of possible improvements. I really hope this Addon isn't dead because it have so much potencial.

Bugs:
- [x] High CPU usage #52  #47 #22 #21 (fixed)
- [ ] Counter doesnt work for pinned Tabs #45  
- [ ] Tab count out of sync for removed tabs #11
- [ ] Siderbar doesnt automatically refresh after renaming Container Details #39 
- [ ] Open all Bookmarks in tabs but in the wrong container #46 
- [ ] Some favicons won't load #21
- [ ] Disable Scrolling by default #58 
- [ ] Clicking any tab of a hidden container should show that container #36
- [ ] Sometimes Graphical Bug after unpin tab.

Features:
- [ ] Show more than one Container #1  #42 
       Possibility to expand more than one Container at the same time and dont close last container.
- [ ] Tab Tree #49  #34 
       Tree Structure for Tabs (compatible with "Tree Style Tab")
- [ ] Tab Folders #57 
       Create a collapsible (Tree) folder within containers to organize tabs.
- [ ] Toolbar Button #50   
       Quick access toolbar button for Sea Containers 
- [ ] Tab counter (window) in Sidebar Title   
- [ ] Favicon and Container Sound
       Show Sound icon and allow to enable/disable sound with click on tab/container favicon
       Always disable sound for all/new tabs if sound is disabled in container
       Double click on pinned tabs
- [ ] Drag'n'Drop tabs into other containers
- [ ] Light/Dark Theme support
- [ ] Improved Context Menü
- [ ] Double Click on Container Name open a new Tab in this Container
- [ ] Double Click on free space open a new tab in the actual Container
- [ ] Search/Filter Bar #50 
- [ ] It would be great to bring a "standard" for Tree Tabs 
- [ ] Compatible with Tree Style Tab, Tree Tabs, Conex (Panorama Replacement)

Options:
- [ ] Change Container hight and text size with %
- [ ] Change Tab hight and text size with %
- [ ] Change Searchbar hight and text size with %
- [ ] Change Tab color background and text for normal, active, discarded
- [ ] Show/Hide Searchbar
- [ ] Always show hidden Tabs.
- [ ] Option to remember "Tab and Container Sound" settings after closing Firefox.
- [ ] Always create a new tab in the last expanded container not in the container of the actual tab.
- [ ] Allow Drag'n'Drop to other containers. (Privacy Warning!) #41 
- [x] Change shortcut for Sea Container (Waiting for FF67) (STRG+,) #50
- [ ] Some behavioural options like "Tree Style Tab" would improve the addon

Personally i dont "need" it but much people like the "Panorama" overlay. Take a look at Conex I could imagine that your Addons could grow together to offer a great Tab/Container/Grouping Solution.
